FROM oven/bun:1.4.0@sha256:5ff609364c049b54eb0ff560ec96319729a972078ef2c755d758f0c6ef89c2d6 AS build
WORKDIR /app/web
COPY web/package.json web/bun.lock ./
ENV CI=true
RUN bun install --frozen-lockfile --network-concurrency=4
COPY web .
COPY configs /app/configs
COPY src/vitroctl/image_geometry/dish-recipe.json /app/src/vitroctl/image_geometry/dish-recipe.json
RUN bun run build

FROM oven/bun:1.4.0-slim@sha256:e0ee68d16ccb9927bf02aa7dd8fd4bf3369ee6d46da04faa72b05ce8bfd135f6
WORKDIR /app/web
ENV NODE_ENV=production
COPY web/package.json web/bun.lock ./
RUN bun install --frozen-lockfile --production --network-concurrency=4
COPY --from=build /app/web/dist ./dist
COPY web/drizzle ./drizzle
EXPOSE 3000
CMD ["bun", "dist/server.js"]
