import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import { drizzle as drizzlePostgres } from "drizzle-orm/postgres-js";
import { migrate as migratePostgres } from "drizzle-orm/postgres-js/migrator";

import * as schema from "./schema";

/** A database handle or a transaction on it; modules never depend on the driver. */
export type Executor = PgDatabase<PgQueryResultHKT, typeof schema>;

/**
 * `pglite://` selects an in-process database: in memory when nothing follows,
 * otherwise persisted in the named directory. Tests and single-machine
 * development run against it; deployments use a `postgres://` URL.
 */
const PGLITE_URL = "pglite://";

/** Migrations ship beside the server entry, generated by `bun run db:generate`. */
const MIGRATIONS_FOLDER = `${process.cwd()}/drizzle`;

let ready: Promise<Executor> | undefined;

async function open(): Promise<Executor> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is required");
  }
  if (url.startsWith(PGLITE_URL)) {
    // PGlite is a development dependency; production images never load it.
    const [{ drizzle }, { migrate }] = await Promise.all([
      import("drizzle-orm/pglite"),
      import("drizzle-orm/pglite/migrator"),
    ]);
    const dataDir = url.slice(PGLITE_URL.length);
    const db = dataDir
      ? drizzle({ connection: { dataDir }, schema })
      : drizzle({ schema });
    await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
    return db;
  }
  const db = drizzlePostgres({
    connection: { url, onnotice: () => {} },
    schema,
  });
  await migratePostgres(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return db;
}

/** The migrated application database, opened on first use. */
export function database(): Promise<Executor> {
  ready ??= open().catch((error: unknown) => {
    ready = undefined;
    throw error;
  });
  return ready;
}

/** Runs `work` inside one transaction on the application database. */
export async function transaction<T>(
  work: (tx: Executor) => Promise<T>,
): Promise<T> {
  const db = await database();
  return db.transaction((tx) => work(tx));
}
