import type { PgDatabase, PgQueryResultHKT } from "drizzle-orm/pg-core";
import { drizzle as drizzlePostgres } from "drizzle-orm/postgres-js";
import { migrate as migratePostgres } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";

import { installBuiltins } from "./registry";
import * as schema from "./schema";

/** A database handle or a transaction on it; modules never depend on the driver. */
export type Executor = PgDatabase<PgQueryResultHKT, typeof schema>;

/**
 * `pglite://` selects an in-process database: in memory when nothing follows,
 * otherwise persisted in the named directory. Tests and single-machine
 * development run against it; deployments use a `postgres://` URL.
 */
const PGLITE_URL = "pglite://";

/** Migrations ship beside the server entry, generated by `bun run db:generate`. */
const MIGRATIONS_FOLDER = `${process.cwd()}/drizzle`;

/**
 * The workbench runs as one replica, so a single modest pool serves every
 * request and the rest of the database server's connection budget stays free
 * for whoever else needs it.
 */
const POOL_SIZE = 10;

/** A driver's open database together with the operations only it can perform. */
export interface Connection {
  db: Executor;
  migrate: () => Promise<void>;
  close: () => Promise<void>;
}

/** Opens the database `url` names, without touching it. */
async function connect(url: string): Promise<Connection> {
  if (url.startsWith(PGLITE_URL)) {
    // PGlite is a development dependency; production images never load it.
    const [{ drizzle }, { migrate }] = await Promise.all([
      import("drizzle-orm/pglite"),
      import("drizzle-orm/pglite/migrator"),
    ]);
    const dataDir = url.slice(PGLITE_URL.length);
    const db = dataDir
      ? drizzle({ connection: { dataDir }, schema })
      : drizzle({ schema });
    return {
      db,
      migrate: () => migrate(db, { migrationsFolder: MIGRATIONS_FOLDER }),
      close: () => db.$client.close(),
    };
  }
  const client = postgres(url, { max: POOL_SIZE, onnotice: () => {} });
  const db = drizzlePostgres(client, { schema });
  return {
    db,
    migrate: () => migratePostgres(db, { migrationsFolder: MIGRATIONS_FOLDER }),
    close: () => client.end(),
  };
}

/**
 * Brings an open connection to a state fit to serve. Preparation owns the
 * connection until it succeeds: a failure releases it, so a caller that keeps
 * retrying a database it cannot migrate opens one pool per attempt otherwise,
 * and reaches the server's connection limit while the fault is still there.
 */
export async function prepare(connection: Connection): Promise<Executor> {
  try {
    await connection.migrate();
    await installBuiltins(connection.db);
  } catch (error) {
    await connection.close();
    throw error;
  }
  return connection.db;
}

async function open(): Promise<Executor> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is required");
  }
  return prepare(await connect(url));
}

/**
 * A connection outlives the module that opened it: the dev server replaces
 * server modules on every edit, and a handle held in module scope would strand
 * its pool on each reload until the database refuses new connections. The
 * process owns the pool, so the runtime is where it lives.
 */
interface DatabaseHandle {
  ready?: Promise<Executor>;
}

const HANDLE: unique symbol = Symbol.for("vitroflow.database");
const runtime = globalThis as typeof globalThis & {
  [HANDLE]?: DatabaseHandle;
};
const handle: DatabaseHandle = (runtime[HANDLE] ??= {});

/** The migrated application database with its builtin models, opened on first use. */
export function database(): Promise<Executor> {
  handle.ready ??= open().catch((error: unknown) => {
    handle.ready = undefined;
    throw error;
  });
  return handle.ready;
}

/** Runs `work` inside one transaction on the application database. */
export async function transaction<T>(
  work: (tx: Executor) => Promise<T>,
): Promise<T> {
  const db = await database();
  return db.transaction((tx) => work(tx));
}

/** Join an existing unit of work or open one for a standalone domain call. */
export function inTransaction<T>(
  executor: Executor | undefined,
  work: (tx: Executor) => Promise<T>,
): Promise<T> {
  return executor ? work(executor) : transaction(work);
}
